-- MySQL Script generated by MySQL Workbench
-- Wed Aug  2 19:52:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gaalerie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gaalerie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gaalerie` DEFAULT CHARACTER SET utf8 ;
USE `gaalerie` ;

-- -----------------------------------------------------
-- Table `gaalerie`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaalerie`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gaalerie`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaalerie`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `adm` TINYINT NOT NULL DEFAULT 0,
  `address` INT NOT NULL,
  INDEX `address_idx` (`address` ASC) VISIBLE,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `address`
    FOREIGN KEY (`address`)
    REFERENCES `gaalerie`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gaalerie`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaalerie`.`purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `total` FLOAT NOT NULL,
  `liberated` TINYINT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `gaalerie`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gaalerie`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaalerie`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `artist` VARCHAR(150) NOT NULL,
  `price` FLOAT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `technique` VARCHAR(45) NOT NULL,
  `dimension` VARCHAR(45) NOT NULL,
  `available` TINYINT NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  `purchase` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `purchase_idx` (`purchase` ASC) VISIBLE,
  CONSTRAINT `purchase`
    FOREIGN KEY (`purchase`)
    REFERENCES `gaalerie`.`purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
